### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by HsLeo** [vqnhat/DSN-Binarization#2]
when I do the command :sudo make all -j4

PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/net.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/adadelta_solver.cpp
CXX src/caffe/solvers/adam_solver.cpp
In file included from /home/rb505/caffe/include/caffe/solver.hpp:8:0,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/adadelta_solver.cpp:3:
./include/caffe/solver_factory.hpp: In static member function ‘static caffe::Solver<Dtype>* caffe::SolverRegistry<Dtype>::CreateSolver(const caffe::SolverParameter&)’:
./include/caffe/solver_factory.hpp:74:32: error: ‘const class caffe::SolverParameter’ has no member named ‘type’
     const string& type = param.type();
                                ^
Makefile:519: recipe for target '.build_release/src/caffe/solvers/adadelta_solver.o' failed
make: *** [.build_release/src/caffe/solvers/adadelta_solver.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /home/rb505/caffe/include/caffe/solver.hpp:8:0,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/sgd_solver.cpp:4:
./include/caffe/solver_factory.hpp: In static member function ‘static caffe::Solver<Dtype>* caffe::SolverRegistry<Dtype>::CreateSolver(const caffe::SolverParameter&)’:
./include/caffe/solver_factory.hpp:74:32: error: ‘const class caffe::SolverParameter’ has no member named ‘type’
     const string& type = param.type();
                                ^
Makefile:519: recipe for target '.build_release/src/caffe/solvers/sgd_solver.o' failed
make: *** [.build_release/src/caffe/solvers/sgd_solver.o] Error 1
In file included from /home/rb505/caffe/include/caffe/solver.hpp:8:0,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/adam_solver.cpp:3:
./include/caffe/solver_factory.hpp: In static member function ‘static caffe::Solver<Dtype>* caffe::SolverRegistry<Dtype>::CreateSolver(const caffe::SolverParameter&)’:
./include/caffe/solver_factory.hpp:74:32: error: ‘const class caffe::SolverParameter’ has no member named ‘type’
     const string& type = param.type();
                                ^
Makefile:519: recipe for target '.build_release/src/caffe/solvers/adam_solver.o' failed
make: *** [.build_release/src/caffe/solvers/adam_solver.o] Error 1

how can I fix it?
I tried all solve method in the google , it doesn't work :(

My environment
CUDA:9.0
GPU:1080Ti 
driver:390

**Comment by vqnhat** [comment]
Since this is the problem of compiling the caffe and DSN, I would suggest posting an issue at https://github.com/BVLC/caffe and https://github.com/s9xie/hed
