### ISSUE TITLE
can not load image

### ISSUE THREAD

**Issue by justinner** [vqnhat/DSN-Binarization#3]
Hi,I am sorry to bother you again,I have downloaded your total source,and I want to train,but I met the problem ,

/../data/binarization/train_pair_for_2011.lst
I1214 11:25:34.042053  6563 image_labelmap_data_layer.cpp:50] Shuffling data
I1214 11:25:34.060681  6563 image_labelmap_data_layer.cpp:55] A total of 84210 images.
E1214 11:25:34.060843  6563 io.cpp:77] Could not open or find file ../../../data/binarization/train_data\028923_45.png
E1214 11:25:34.060851  6563 io.cpp:77] Could not open or find file ../../../data/binarization/train_data\028923_45_gt.png
F1214 11:25:34.060855  6563 image_labelmap_data_layer.cpp:84] Check failed: cv_img.data Could not load train_data\028923_45.png
*** Check failure stack trace: ***
已放弃 (核心已转储)

Even if I deleted the image,I still had the error but not the same image,could you help me?

**Comment by justinner** [comment]
hi,Vqnhat,I have run your code successfully,but when I try to modify the train_val_conv3.prototxt,the error was 
input + output channels need to be the same
I add upsample layer,I want to ask if the error is important,or can I ignore

**Comment by vqnhat** [comment]
Hi,

About this problem, I guess you should check the output of your modified network. If there are no problem with the generated images, you can ignore the error message.

**Comment by justinner** [comment]
OK,thanks very much,I will try again.
