### ISSUE TITLE
Bickley diary dataset

### ISSUE THREAD

**Issue by bendikhk** [vqnhat/DSN-Binarization#4]
Hi, great project!
Thanks for a great project and dataset. Would it be possible for you to share the Bickley dataset? I want to do some tests with a different preprocessing step for the training data, and I'm not able to find the Bickley dataset anywhere.

**Comment by vqnhat** [comment]
Hi,

This is the Bickley diary dataset. 

[original_gt_labeled.zip](https://github.com/vqnhat/DSN-Binarization/files/2793688/original_gt_labeled.zip)

**Comment by bendikhk** [comment]
Thank you! :)
